[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized" # "Windowed" | "Maximized" | "Fullscreen"
title = "Alacritty"
dynamic_title = true
blur = true
#opacity = 0.9 # distracting
padding.x = 5
padding.y = 2

[cursor]
style = { shape= "Beam", blinking = "on" }
thickness = 0.2
blink_interval = 600 #ms
blink_timeout = 0
unfocused_hollow = false

[scrolling]
history = 2500
multiplier = 10

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono"
normal.style = "Regular"
size = 13

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[general]
live_config_reload = true
working_directory = "None"

#Theme
#import = ["~/.config/alacritty/your-theme.toml",]
