live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  # -- Themes --
  # "~/.config/alacritty/nordic.toml",
]

[window]
title = "Alacritty"
#decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

#[window.dimensions]
#columns = 155
#lines = 35

[cursor.style]
shape= "Beam"
#blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "JetBrainsMono"
normal.style = "Regular"
size = 12

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"
style = "Italic"
